### ISSUE TITLE
Is there any reference paper for this repository?

### ISSUE THREAD

**Issue by Wesley273** [dorian-roux/ing3-optimisation-metaheuristiques#1]
thanks a lot

**Comment by dorian-roux** [comment]
This repository was developed as part of an artificial intelligence course at a French engineering school. In its construction, we utilized a thesis from a student at the university on NSGA-II for task offloading that has not been published to date. However, among the references for this work are notably:
- "_Efficient energy and completion time for dependent task computation offloading algorithm in industry 4.0_" by Rabab Farouk Abdel-Kader, Noha Emad El-Sayad, and Rawya Yehia Rizk.
- "_Parallel Meta-Heuristics for Solving Dynamic Offloading in Fog Computing_" by Samah Ibrahim AlShathri, Samia Allaoua Chelloug, and Dina S. M. Hassan.
- "_Joint optimization of energy consumption and time delay in IoT-fog-cloud computing environments using NSGA-II metaheuristic algorithm_" by Vahid Jafari and Mohammad Hossein Rezvani.

From these articles, you can deepen your understanding of this repository. However, I want to remind you that this project offers an understanding and functionality of the NSGA II model without necessarily being a reference, as it was a project with a relatively short deadline.

**Comment by Wesley273** [comment]
thanks a lot
